# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 771)
        MainWindow.setMinimumSize(QtCore.QSize(881, 690))
        MainWindow.setMaximumSize(QtCore.QSize(881, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 881, 671))
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.table_register = QtWidgets.QTableWidget(self.tab)
        self.table_register.setGeometry(QtCore.QRect(10, 10, 851, 571))
        self.table_register.setObjectName("table_register")
        self.table_register.setColumnCount(6)
        self.table_register.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(5, item)
        self.table_register.horizontalHeader().setDefaultSectionSize(140)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.table_my = QtWidgets.QTableWidget(self.tab_2)
        self.table_my.setGeometry(QtCore.QRect(10, 50, 591, 231))
        self.table_my.setObjectName("table_my")
        self.table_my.setColumnCount(4)
        self.table_my.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_my.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_my.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_my.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_my.setHorizontalHeaderItem(3, item)
        self.table_my.horizontalHeader().setDefaultSectionSize(145)
        self.btn_sale = QtWidgets.QPushButton(self.tab_2)
        self.btn_sale.setGeometry(QtCore.QRect(650, 150, 93, 28))
        self.btn_sale.setObjectName("btn_sale")
        self.table_my_sale = QtWidgets.QTableWidget(self.tab_2)
        self.table_my_sale.setGeometry(QtCore.QRect(10, 350, 711, 231))
        self.table_my_sale.setObjectName("table_my_sale")
        self.table_my_sale.setColumnCount(5)
        self.table_my_sale.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_my_sale.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_my_sale.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_my_sale.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_my_sale.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_my_sale.setHorizontalHeaderItem(4, item)
        self.table_my_sale.horizontalHeader().setDefaultSectionSize(140)
        self.btn_cancel = QtWidgets.QPushButton(self.tab_2)
        self.btn_cancel.setGeometry(QtCore.QRect(730, 440, 131, 28))
        self.btn_cancel.setObjectName("btn_cancel")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(20, 320, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.table_sale = QtWidgets.QTableWidget(self.tab_3)
        self.table_sale.setGeometry(QtCore.QRect(10, 10, 851, 571))
        self.table_sale.setObjectName("table_sale")
        self.table_sale.setColumnCount(6)
        self.table_sale.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(5, item)
        self.table_sale.horizontalHeader().setDefaultSectionSize(140)
        self.btn_buy = QtWidgets.QPushButton(self.tab_3)
        self.btn_buy.setGeometry(QtCore.QRect(750, 600, 93, 28))
        self.btn_buy.setObjectName("btn_buy")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 10, 51, 30))
        self.label_3.setObjectName("label_3")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 51, 30))
        self.label_1.setObjectName("label_1")
        self.label_address = QtWidgets.QLabel(self.centralwidget)
        self.label_address.setGeometry(QtCore.QRect(70, 10, 461, 30))
        self.label_address.setText("")
        self.label_address.setObjectName("label_address")
        self.label_balance = QtWidgets.QLabel(self.centralwidget)
        self.label_balance.setGeometry(QtCore.QRect(610, 10, 241, 30))
        self.label_balance.setText("")
        self.label_balance.setObjectName("label_balance")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Личный кабинет"))
        item = self.table_register.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_register.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Адрес"))
        item = self.table_register.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Общая площадь"))
        item = self.table_register.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Срок эксплуатации"))
        item = self.table_register.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Собственник"))
        item = self.table_register.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Цена"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Общий реестр"))
        item = self.table_my.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_my.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Адрес"))
        item = self.table_my.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Общая площадь"))
        item = self.table_my.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Срок эксплуатации"))
        self.btn_sale.setText(_translate("MainWindow", "Продать"))
        item = self.table_my_sale.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_my_sale.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Адрес"))
        item = self.table_my_sale.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Общая площадь"))
        item = self.table_my_sale.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Срок эксплуатации"))
        item = self.table_my_sale.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Цена"))
        self.btn_cancel.setText(_translate("MainWindow", "Отменить продажу"))
        self.label.setText(_translate("MainWindow", "Продается"))
        self.label_2.setText(_translate("MainWindow", "Моя недвижимость"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Моя недвижимость"))
        item = self.table_sale.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_sale.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Адрес"))
        item = self.table_sale.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Общая площадь"))
        item = self.table_sale.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Срок эксплуатации"))
        item = self.table_sale.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Собственник"))
        item = self.table_sale.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Цена"))
        self.btn_buy.setText(_translate("MainWindow", "Купить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Продажи"))
        self.label_3.setText(_translate("MainWindow", "Баланс:"))
        self.label_1.setText(_translate("MainWindow", "Адрес:"))
